name: 我觉得有一个功能还能更好
description: 点击此项对已有功能提出优化建议
title: '[功能++?]: '
labels: [ "enhancement" ]
assignees: []
projects: []
# type: feature   # 组织级功能：个人仓库校验不通过，如需启用请取消注释

body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您愿意花一些时间来填写这个内容！
        ## 以下是一些注意事项，能让提交更快被处理

        ### ❗ | 确定没有相同提议的 ISSUE 已被提出。
        ### ❔ | 提议时，如果文字无法说明清楚，不妨使用画图的方法辅助说明
        ### ⚠ | 如果涉及敏感信息，请自行打码

        ## 提问指引
        [《提问的智慧》](https://lug.ustc.edu.cn/wiki/doc/smart-questions/)

        ---
  - type: checkboxes
    id: terms
    attributes:
      label: |
        请确保您已阅读以上注意事项，并勾选下方的确认框。
      options:
        - label: "我已经仔细阅读上述注意事项，并能够尝试运用其中任一文档所述的提问技巧。"
          required: true
        - label: "我确定这不是一个伪需求，他能解决实际存在的问题。"
          required: true
        - label: "我确定这是一个有意义建议，且目前似乎没有其他更好的解决方案。"
          required: true
        - label: "我确定在最新版本中没有这个功能"
          required: true
        - label: "我愿意为此功能提交 Pull Request，或者提供一些实现思路（非必选）"
          required: false

  - type: markdown
    attributes:
      value: |
        接下来我们将引导您详细地描述您的建议

  - type: input
    id: name
    attributes:
      label: 功能名称
      description: 你要对哪个功能进行增强？
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 简述这个增强功能是干嘛的
    validations:
      required: true

  - type: textarea
    id: mean
    attributes:
      label: 新功能意义
      description: 简述这个增强功能的意义在哪，比如用途，或者你怎么想到这个建议的
    validations:
      required: true

  - type: dropdown
    id: part-type
    attributes:
      label: 优化作用于哪个工种 / 模块？
      description: 可多选；如果您确实不知道属于什么，可以选择 “我不确定”
      multiple: true
      options:
        - Sisyphus（总调度）
        - Hermes（快速执行）
        - Explore（检索）
        - Librarian（文档）
        - Multimodal Looker（看图）
        - Hephaestus（写代码）
        - Prometheus（规划）
        - Oracle（调试/终验）
        - client UI（面板/设置页）
        - 我不确定
    validations:
      required: true

  - type: textarea
    id: how-to
    attributes:
      label: 实现方案（可选）
      description: 如果您有什么好的实现方案，那么可以写在这里

  - type: textarea
    id: extra-desc
    attributes:
      label: 补充说明（可选）
